server:
  port: 8080

spring:
  application:
    name: spring-ai-hello-world

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.4:3306/chatMemory?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql_JXchxh
logging:
  level:
    org.springframework.ai: DEBUG